dealer_name:Deepak Yadav,
    email:yadavdeepak486@gmail.com,
    master_oil_company:Bharat Petroleum,
    location:AB Road,Mangliya,
    omc_customer_code:BP1000897239873,
    state:Madhya Pradesh,
    district:Indore,
    total_no_mpd:3,
    total_no_bay:6,
    total_no_nozzles:12,
    total_no_tanks:3,
    total_no_air_machine:1,
    puc_machine:1,
    any_other_facility:1